services:
    g48wk8goo88g8k8cw4cs484g-131824895739:
        image: 'g48wk8goo88g8k8cw4cs484g:af1cdb1125294045da06fd3249f98378f2cd6d7b'
        container_name: g48wk8goo88g8k8cw4cs484g-131824895739
        restart: unless-stopped
        expose:
            - '3000'
        networks:
            coolify:
                aliases:
                    - g48wk8goo88g8k8cw4cs484g-131824895739
        mem_limit: '0'
        memswap_limit: '0'
        mem_swappiness: 60
        mem_reservation: '0'
        cpus: 0.0
        cpu_shares: 1024
        env_file:
            - .env
        labels:
            - traefik.enable=true
            - traefik.http.middlewares.gzip.compress=true
            - traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https
            - traefik.http.routers.http-0-g48wk8goo88g8k8cw4cs484g.entryPoints=http
            - traefik.http.routers.http-0-g48wk8goo88g8k8cw4cs484g.middlewares=redirect-to-https
            - traefik.http.routers.http-0-g48wk8goo88g8k8cw4cs484g.rule=Host(`fisio.furquim.cloud`)
            - traefik.http.routers.http-0-g48wk8goo88g8k8cw4cs484g.service=http-0-g48wk8goo88g8k8cw4cs484g
            - traefik.http.routers.https-0-g48wk8goo88g8k8cw4cs484g.entryPoints=https
            - traefik.http.routers.https-0-g48wk8goo88g8k8cw4cs484g.middlewares=gzip
            - traefik.http.routers.https-0-g48wk8goo88g8k8cw4cs484g.rule=Host(`fisio.furquim.cloud`)
            - traefik.http.routers.https-0-g48wk8goo88g8k8cw4cs484g.service=http-0-g48wk8goo88g8k8cw4cs484g
            - traefik.http.routers.https-0-g48wk8goo88g8k8cw4cs484g.tls=true
            - traefik.http.routers.https-0-g48wk8goo88g8k8cw4cs484g.tls.certresolver=letsencrypt
            - traefik.http.services.http-0-g48wk8goo88g8k8cw4cs484g.loadbalancer.server.port=3000
            - caddy_0.encode=zstd gzip
            - caddy_0.handle_path.0_reverse_proxy={{upstreams 3000}}
            - caddy_0.handle_path=/*
            - caddy_0.header=-Server
            - caddy_0.try_files={path} /index.html /index.php
            - caddy_0=https://fisio.furquim.cloud
            - caddy_ingress_network=coolify
            - coolify.managed=true
            - coolify.version=4.0.0-beta.463
            - coolify.applicationId=1
            - coolify.type=application
            - coolify.name=g48wk8goo88g8k8cw4cs484g
            - coolify.resourceName=fabioafurquimgestaofurquimmain-i8o8ckoockocsscg4oo880w8
            - coolify.projectName=gestao-furquim
            - coolify.serviceName=fabioafurquimgestaofurquimmain-i8o8ckoockocsscg4oo880w8
            - coolify.environmentName=production
            - coolify.pullRequestId=0
networks:
    coolify:
        external: true
        name: coolify
        attachable: true
